### ISSUE TITLE
Asking Questions

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#12]
_This is assignment 12 and is due on Feb 02, 2015._
- Create an array of questions (Strings)
- Iterate over the array using each, asking each question to the user
- Bonus: Save all the answers with the questions, and print a summary at the end

**Comment by brianburridge** [comment]
@markbiz41 What I'm looking for here is one array with multiple questions. Then as the 2nd bullet indicates, you would use the `each` command to iterate over them and ask them all. Currently you've created three different arrays. This will make it difficult in the future to simply add another question to the array. In your code, you would have to add another entire section of code to ask one more question. But what if your app had to ask 100 questions? It would become quite long using that strategy.

**Comment by markbiz41** [comment]
@brianburridge 
Assignment #12 re-done.

**Comment by brianburridge** [comment]
What I'm looking for is an interview style. The app asks a question and lets the user answer. Then asks another question and lets them answer. So on until all questions have been asked.

Also, your each statement isn't setup properly and isn't really iterating over the questions.  Read through this and see if it helps: http://learnrubythehardway.org/book/ex32.html

**Comment by markbiz41** [comment]
@brianburridge 
Brian, I read the LearnRubyTheHardWay.org and I have tried different ways to use the code but to no avail.  I have read the article numerous times and I am still not coming up with any solutions.  My code is:

question_user = ["What is your name? #{answers}", "Where do you live? #{answers}", "What is your favorite food? #{answers}"]
question_user.each do |question|
puts "#{question}"
answers = gets.chomp.each do |answer|
  puts "#{answer}"
end
end

This is my code above.  Any suggestions on what I am doing wrong?

**Comment by markbiz41** [comment]
https://gist.github.com/markbiz41/618ad0a2406e72d22beb

**Comment by brianburridge** [comment]
I commented in the gist.

**Comment by brianburridge** [comment]
:+1:
