### ISSUE TITLE
Classy Pig Latin

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#14]
_This is assignment 14 and is due on Feb 02, 2015._
- Using the structure of a class as I've laid out in this [gist](https://gist.github.com/brianburridge/7e98d358dee03c6b6060), finishing creating the PigLatin class to translate a word into pig latin
- Bonus: modify the app to convert an entire phrase (one word at a time)
- Note the pig latin rules in the comment of the skeleton app

**Comment by markbiz41** [comment]
@brianburridge 
I am having trouble with this assignment.  My code is below.  What am I doing wrong.

# Note for this exercise, follow these simplified pig latin rules
# If the first letter is a vowel, add "way" to the end
# If the first letter is a consonant, move it to the end and add "ay"

class PigLatin
  VOWELS =  %w(a e i o u)

  def self.pigatize(passed_text)

    # Check to see if the first letter is a vowel, if not it's a consonant
    if PigLatin.starts_with_vowel(passed_text[0])
      # this is placeholder code and should take action based on it starting with a vowel
      pigatized_text = passed_text
    else
      # this is placeholder code and should take action based on it starting with a consonant
      pigatized_text = passed_text
    end
    return pigatized_text
  end

  # Check to see if the first letter is a vowel
  def self.starts_with_vowel(first_letter)
    # this should determine if it starts with a vowel
    return first_letter
  end
end

puts "Please enter a word and I will translate to pig latin"
text = gets.chomp.split()
if passed_text[0] = ("a")
  puts pigatized_text + "way"
if passed_text[0] = ("e")
  puts pigatized_text + "way"
if passed_text[0] = ("i")
  puts pigatized_text + "way"
if passed_text[0] = ("o")
  puts pigatized_text + "way"
if passed_text[0] = ("u")
  puts pigatized_text + "way"
else
  puts pigatized_text + "ay"
end
end
end
end
end
puts "Pigatized: #{PigLatin.pigatize(text)}"

**Comment by markbiz41** [comment]
I spent Saturday trying to figure out out how to work this Piglatin.  I even went so far as to draw a diagram thinking it would help.  I know this assignment is going to get kicked back to me.  I have on this date seven additional assignments to work on.  I don't know how long each assignment is going to take me but I'm going to do my best.

**Comment by brianburridge** [comment]
Hi @markbiz41 

Did you run this to see if it produce a pig latin version of the word the user entered?

**Comment by brianburridge** [comment]
:+1:
