### ISSUE TITLE
Load questions from a file

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#15]
_This is assignment 15 and is due on Feb 02, 2015._
- Copy and then modify assignment 12 to read the questions from a file instead of the hard coded array
- Load them into an array so the rest of the program can remain the same
- If your assignment 12 is coded correctly, you won't have to change the part that asks questions
- Can be done with two lines of code
- Remember to have the text file of questions in the same directory where your Ruby code is

**Comment by brianburridge** [comment]
@markbiz41 you'll need to check in the _question.txt_ file so I can run this. thanks.

**Comment by markbiz41** [comment]
@brianburridge 
script.txt file sent over to Github for review.

**Comment by brianburridge** [comment]
it's the _questions.txt_ that I need. That isn't in GitHub yet.

**Comment by markbiz41** [comment]
@brianburridge 
Assignment #15 completed into questions.txt

**Comment by brianburridge** [comment]
@markbiz41 This doesn't run at all because there is no file named _question.txt_ checked in. There is a _questions.txt_ but the code isn't looking for that. Also, that file is full of HTML instead of 3 lines of questions.

One other note, your each statement isn't starting an each block as it should and therefore not doing any iteration. An each block has a do and an end, like this:

```
ary.each do |i|
   puts i
end
```

**Comment by markbiz41** [comment]
See 15.rb

**Comment by brianburridge** [comment]
@markbiz41 see my comment above.

**Comment by brianburridge** [comment]
@markbiz41 I removed the _completed_ tag because this doesn't work, and I referred you to my comment above on what's wrong with it. You didn't modify the code at all, but yet marked it _completed_ again.

**Comment by brianburridge** [comment]
:+1:
