### ISSUE TITLE
Parsing JSON

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#17]
_This is assignment 17 and is due on Feb 03, 2015._
- Read about [HTTP](http://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol)
- Read review on [using JSON in Ruby](https://hackhands.com/ruby-read-json-file-hash/)
- Look thru some [JSON Examples](http://json.org/example)
- Copy assignment 15 and modify to now read in questions from a JSON file
- This means you need to create a JSON file of you questions
- Read and parse the JSON into an array so the rest of the app remains the same

**Comment by brianburridge** [comment]
I Can't find the code for this one. Where is it?

**Comment by markbiz41** [comment]
See 17.rb

**Comment by brianburridge** [comment]
This doesn't run @markbiz41 

Can you try running this on your computer and see if it runs for you? If so, please come see me and we'll look at it together.

Also, this is loading both a JSON and a TXT file for questions. You only want to load questions from a JSON file for this assignment.

**Comment by brianburridge** [comment]
You have most of the code in place, but the process is a little mixed up. Instead of setting the questions via an array on line 1 (like in assignment #15 ) you should set them by reading them in from a JSON file as you are on line 8. Then once you do read them in, you need to parse them (like you are on line 9), but then you have to use the parsed result to ask the questions to the user (again instead of using the array from line 1 to do it).

**Comment by markbiz41** [comment]
@brianburridge 
17.rb just re-done.

**Comment by brianburridge** [comment]
@markbiz41 So this works, however, it's not reading in the questions from JSON. You are doing that on line 2, but then you load a new file in on line 4. Those are the text based questions. Take a look at that and let me know if that makes sense.

**Comment by markbiz41** [comment]
@brianburridge 
17.rb now works with json.

**Comment by brianburridge** [comment]
Yep! :+1:
