### ISSUE TITLE
Movie Querying script

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#18]
_This is assignment 18 and is due on Feb 04, 2015._
- http://developer.rottentomatoes.com/
- Use Rotten Tomato's movie querying script to create a command line app which prompts the user for a movie title
- Using the entered movie title, search via the API for the movie's synopsis and output to the user
- If more than one movie comes back, show all the movie title matches with their synopsis

**Comment by brianburridge** [comment]
This should fetch the movie's synopsis using the API and output it to the user. Currently you aren't searching the API for a specific movie so you get no information back in your API call.

**Comment by markbiz41** [comment]
@brianburridge 
I believe I completed all the bullet-points to assignment #18

**Comment by markbiz41** [comment]
@brianburridge 
Assignment #18 redone

**Comment by brianburridge** [comment]
:+1:
