### ISSUE TITLE
Extending String with PigLatin

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#20]
_This is assignment 19 and is due on Feb 04, 2015._

Extend Ruby's String class to have a "pigatize" method that will turn any string into pig latin.

Should use the same code you wrote before, but now you are extending the String class and putting the functionality in there.

**Comment by markbiz41** [comment]
@brianburridge 
Assingment #19 done and working.

**Comment by brianburridge** [comment]
@markbiz41 This doesn't seem to be any different than your assignment 14. It should, however, be different, because here we are extending Ruby's String class to now have a "pigatize" method.

When working, you would then be able to call it like this:

```
    text.pigatize
```

Instead of:

```
    PigLatin.pigatize(text)
```

**Comment by markbiz41** [comment]
@brianburridge 
Assignment #19 using extended String class.

**Comment by brianburridge** [comment]
:+1:
