### ISSUE TITLE
Invoicing

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#23]
_This is assignment 23 and is due on Feb 09, 2015._
- Create an InvoiceItem class and an Invoice class (two classes in two separate files)
- The InvoiceItem class should have the following attributes: product_name, sale_price, quantity, tax percentage
- The invoice class should have a getter and setter for an attribute called: _items_ to hold an array of all the InvoiceItems
- Create an instance method in Invoice that will calculate a total of all it's invoice items
- Use reject or select methods in order to remove any InvoiceItem objects that have a zero quantity
- Create an instance method in Invoice to sum up the invoice items and get a total
- Ask the user to enter in the attributes for each invoice item, hitting ENTER on product name when done
- With each invoice item entered, create the object and add it to the collection of invoice items within a single Invoice object.
- Then output each line item.
- Show a sub-total without the tax, then a line item for the tax, then the total.
- Bonus: make the invoice look like a real world invoice in the terminal

**Comment by markbiz41** [comment]
@brianburridge 
I have done assignment #23 regarding Invoicing.

**Comment by brianburridge** [comment]
In InvoiceItem you have two methods, `invoice_total` and `invoice_sum`. It does not look like you are using either of these. You calculate the totals in `main.rb`.

Also, take a look at the 5th bullet functionality. You don't have that in here. There should also be an instance method to get the invoice total in the Invoice model (bullet 6), instead of in the InvoiceItem as you have it, and instead of calculating the total as you go as you are currently doing.

Also, in `main.rb`, you are adding the invoice item to the invoice before you even put any of the values in. It's working because Ruby keeps a pointer to the object, so it's letting you set the variables AFTER you add it to the invoice. But, it would be much better if you set all the invoice item's attributes first, then add it to the array of items.

**Comment by markbiz41** [comment]
@brianburridge 
I have worked on assignment #23.rb to do the suggestions you made.

**Comment by brianburridge** [comment]
@markbiz41 In the future, it would be best to name your files to match the class names. So in this case you would have `invoice.rb` and `invoice_item.rb`, just like we do with our Rails models and controllers.

But you've fulfilled all the requirements here and the code looks clean. :+1:
