### ISSUE TITLE
Create a blog

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#29]
_This is assignment 28 and is due on Feb 11, 2015._
- Read [Separation of Concerns](http://en.wikipedia.org/wiki/Separation_of_concerns)
- Read [MVC](http://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller)
- Refer to [HTML Element Reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element)
- Refer to [CSS Reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element)
- Create a home page with the title of your blog, and your name as the author
- List out at least 3 pretend blog posts with their title, word count and summary. Hyperlinking them to their own HTML Post pages.
- On the individual Post pages, should show a link back to the home page, the blog title, the post title, the body, and the published date.
- You should have four HTML files that all link to each other and one external css.
- Include an image in at least one blog post
- Bonus: Use at least one custom font from Google
- Put these files in an _assignment_28_ folder and check into github

**Comment by markbiz41** [comment]
@brianburridge
I have fixed the issues you told me about and changed the color to red so you can read what I had wrote.
