### ISSUE TITLE
More Learning Git/GitHub

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#3]
- Create a folder in the _example_ repo using your first name.
- Add two new files inside the folder. One should be a text file named _aboutme.txt_, in which you tell me five things about yourself. The other can contain anything.
- Push these to the repo.
- Use `git rm filename` to remove the second file (where _filename_ is whatever you named it. Then commit the deletion and push to the repo (removing the file from GitHub too).
- [Read Chapter 1 of the Git book. Sections 1.1 through 1.4 ](http://git-scm.com/book/en/v2/Getting-Started-About-Version-Control)
- Finish [try.github.io](https://try.github.io/) if you didn't finish it for the prework.

**Comment by markbiz41** [comment]
Completed Read Chapter 1 of the Git book
Completed try.github.io

Still working on the other stuff.

**Comment by markbiz41** [comment]
Completed Create a folder in the example repo using your first name.
Completed Add two new files inside the folder. One should be a text file named aboutme.txt, in which you tell me five things about yourself. The other can contain anything.
Completed Push these to the repo.
Completed Use git rm filename to remove the second file (where filename is whatever you named it. Then commit the deletion and push to the repo (removing the file from GitHub too).

**Comment by brianburridge** [comment]
@markbiz41 I don't see your folder or the files in our example repo.

**Comment by markbiz41** [comment]
@brianburridge 
https://gist.github.com/markbiz41/0a5c30c27bfd2a975764

**Comment by markbiz41** [comment]
@brianburridge 
https://gist.github.com/markbiz41/2f7249d1014d19cf5473

**Comment by brianburridge** [comment]
Hi @markbiz41 
This particular assignment required doing the work in the example repository we were using on Monday. It's here: https://github.com/theironyard-tampabay/example

You can see where the other students have created a folder in that repository and added the files to that.

**Comment by markbiz41** [comment]
@brianburridge 
Assignment completed in the Examples page.
