### ISSUE TITLE
Improve the Movie Query app

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#31]
_This is assignment 30 and is due on Feb 16, 2015._
- Alter your existing app so you are no longer returning the synopsis in an instance variable, but instead returning the entire first movie result. We will assume for this exercise that the first movie that comes back is the one we want.
- Using all the information returned for the movie, recreate a movie information page like this one on [IMBD]() or this one on [Rotten Tomatoes](http://www.rottentomatoes.com/m/kingsman_the_secret_service/). Note it does not have to have their branding but should nicely layout as much of the movie information as possible. Ex: poster, ratings, synopsis, tomatometer, some cast, running time, etc.
- The goal is to create your own movie information page as though you were creating one for a client's movie app.

**Comment by markbiz41** [comment]
@brianburridge 
Assignment #31 redone

**Comment by brianburridge** [comment]
@markbiz41 This is a good start, but not quite yet looking like it should. Per the assignment, it should look as much like a real movie page like on Rotten Tomato or IMDB using bootstrap. You are correctly finding some of the data, but your ERB is just dumping some Hashes as they are onto the page, like ratings, posters, and cast.

**Comment by markbiz41** [comment]
@brianburridge 
I used bootstrap.com and wrapbootstrap.com for the free features that I can get.  I have improved the site to where it looks more like Rotten Tomatoes or IMDB.

**Comment by brianburridge** [comment]
@markbiz41 

Definitely looks better. It appears, however, that you have hardcoded the data for cast, the poster image, and the ratings. You are using the API for the synopsis and runtime but not for the rest. All the data on the page should come from the JSON response from the API. Otherwise, when I search for 'Big Hero 6', it tells me that Tom Cruise was in it.

**Comment by markbiz41** [comment]
@brianburridge 
This time assignment #30 is not hard coded.

**Comment by brianburridge** [comment]
:+1:
