### ISSUE TITLE
Validations and Associations

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#35]
_This is assignment 34 and is due on Feb 19, 2015._
- [Read Active Record Validations](http://guides.rubyonrails.org/active_record_validations.html)
- [Read Active Record Associations](http://guides.rubyonrails.org/association_basics.html)
- Continuing with your app from assignment 33, add a second model (use the migration generator) and use a _reference_ and _belongs_to/has_many_ relationship.
- Also add at least three validations between the two models.
- Test your model relationships in the rails console to be sure they work.

**Comment by markbiz41** [comment]
@brianburridge 
Did Assignment #34.

**Comment by brianburridge** [comment]
@markbiz41 There aren't any foreign_keys or references used to setup the model associations here. The last bullet point of this assignment is to test that your relationships work in the console. Be sure to read all the bullet points before turning in an assignment please.

All the information you need to complete this is in the guide listed in bullet two above.

**Comment by brianburridge** [comment]
Mark fulfilled the requirements of this assignment in his final project.
