### ISSUE TITLE
CarrierWave, S3 and environment varaibles

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#38]
_This is assignment 37 and is due on Feb 25, 2015._
- Convert the app from assignment 36 to use [Amazon S3, via Fog](https://github.com/carrierwaveuploader/carrierwave#using-amazon-s3), instead of local file storage.
- Remember to use the [dotenv gem](https://github.com/bkeepers/dotenv) and `heroku config` so you aren't storing your S3 private access keys in GitHub
- Deploy to Heroku (and GitHub as always)
- Please provide the link to the repo AND your Heroku app in a comment here.

**Comment by markbiz41** [comment]
@brianburridge 
This is the Heroku site to see assignment #37: https://markbizblog.herokuapp.com/posts/1

**Comment by brianburridge** [comment]
Did you deploy this latest code to Heroku? Your code shows it setup to go to S3, however, when I upload a photo it's uploading it to Heroku. Which won't work for long (images will eventually be gone).

Can you try pushing to Heroku again and restarting heroku?

**Comment by markbiz41** [comment]
@brianburridge 
The error I made deploying to Heroku was putting all three of my S3 keys in one command line as opposed to doing it three times.  I have deployed to Heroku again but differently.  My Heroku URL is:  markbizblog.heroku.com

**Comment by markbiz41** [comment]
https://markbizblog.heroku.com

**Comment by brianburridge** [comment]
The `dotenv-rails` gem needs to be in your development group. It isn't used for production. Other than that this is working.
