### ISSUE TITLE
Using ActiveAdmin for fully customizable, but quick, back-end admins

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#41]
_This is assignment 40 and is due on Feb 26, 2015._
- Add [ActiveAdmin](https://github.com/activeadmin/activeadmin) to your current application
- Review the [documentation](https://github.com/activeadmin/activeadmin/blob/master/docs/0-installation.md)
- Create an active admin resource for every model in your app
- Do some customization
- Ensure all forms save and allow the user to set the relationships
- Deploy to Heroku
- Paste the link to your Heroku app in a comment here for my review

**Comment by markbiz41** [comment]
@brianburridge 
I have installed ActiveAdmin to the blog app.  The Heroku URL is: https://markbizblog.heroku.com

**Comment by brianburridge** [comment]
I'm not able to edit a User in active admin. It gives an error.

Also, again, not sure which repo in your account is for this app. Can you paste that link in here please?

**Comment by markbiz41** [comment]
@brianburridge 
Updated Active Admin regarding editing a user.  
The Github URL is:  https://github.com/markbiz41/blog/

**Comment by brianburridge** [comment]
:+1:
