### ISSUE TITLE
Using Memoization, Scopes, Flash, and Authorization

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#44]
_This is assignment 43 and is due on Mar 03, 2015._
- [Read about memoization](http://www.justinweiss.com/blog/2014/07/28/4-simple-memoization-patterns-in-ruby-and-one-gem/)
- Review the [ActiveRecord Scopes](http://guides.rubyonrails.org/active_record_querying.html#scopes) guide
- Review using model scopes in [ActiveAdmin](http://activeadmin.info/docs/3-index-pages.html). Scroll down to the _Index Scopes_ section
- Review my [troubleshooting guide](https://github.com/TIY-TSP-Rails-Fall2014/Assignments/blob/master/TroubleshootingGuide.md)
- Read about the [Flash](http://guides.rubyonrails.org/action_controller_overview.html#the-flash)
- Add three scopes to any model and implement in ActiveAdmin too
- Scope all your user owned models (ex. pin and board), and use within your controller so your site cannot be hacked (denying other's from accessing records they don't own).
- Add flash display on site (within layout). Use a flash notice when denying access to a record the user doesn't own. Note: once in the site wide layout, you'll want to remove the notice displays your scaffolding put in place, or you'll have them repeating on those pages.
- Add an `admin` attribute to your user model. Restrict any admin only actions from your views.

**Comment by markbiz41** [comment]
@brianburridge 
I did assignment #43 and the Heroku URL is:  agile-earth-8114.herokuapp.com

**Comment by brianburridge** [comment]
@markbiz41 There are a few items to address for this assignment.

When you add scopes to active admin, you don't have to create all the code for the scope again. You just list which scopes you want to use. See the section title _Index Scopes_ [here](http://activeadmin.info/docs/3-index-pages.html).

Your board controller is not showing boards for the current user, but showing boards for ALL users.

**Comment by markbiz41** [comment]
@brianburridge 
Assignment #43 done.

https://github.com/markbiz41/pinterest/commit/a4357d16b893968a3b2fe3c449a69b1fd8085699

**Comment by brianburridge** [comment]
:+1:
