### ISSUE TITLE
Restricting ActiveAdmin access

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#45]
_This is assignment 44 and is due on Mar 05, 2015._
- Adjust your Pinterest app to only allow "admin" users to access the /admin section

**Comment by markbiz41** [comment]
@brianburridge 
I did restricting ActiveAdmin access for my Pinterest app.  The Heroku URL is:  agile-earth-8114.herokuapp.com

**Comment by brianburridge** [comment]
Not sure why Devise is in your pinterest app. We weren't using any authentication in this app until #54 and there it needs to be the native authentication provided with Rails.

Also, for this code:

``` ruby
rescue_from SecurityError, with: :not_authorized
def authenticate_admin_user!
   raise SecurityError unless current_user.admin == true
end

def not_authorized
   redirect_to root_path, notice: 'Not Authorized! Only Admins Can Access.'
end
```

It probably would have been clearer to just do:

``` ruby
def authenticate_admin_user!
  redirect_to root_path, notice: 'Not Authorized! Only Admins Can Access.' unless current_user.admin
end
```

But it's functional, so closing it out.
