### ISSUE TITLE
Custom Rake Tasks

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#46]
_This is assignment 45 and is due on Mar 05, 2015._
- Read about [Rake tasks in Rails](http://guides.rubyonrails.org/command_line.html#rake)
- Create a custom rake task for your Pinterest app that will output the current count of all your models. Example:
  
  Teams: 4
  Users: 10
  Books: 15
  Authors: 2
  Movies: 1

**Comment by markbiz41** [comment]
@brianburridge 
I did assignment #45 for Custom Rake Tasks.  The Heroku URL is:  agile-earth-8114.herokuapp.com

**Comment by brianburridge** [comment]
@markbiz41 Your rake task should have a namespace around it. Also, I can't even get this app to run. Is it running for you?

**Comment by markbiz41** [comment]
@brianburridge 
Assignment #45 URL is:  https://github.com/markbiz41/pinterest/commit/1983c20103d40e6b129df53489ade114bc85150f

**Comment by markbiz41** [comment]
@brianburridge 
The Pinterest app now runs on Heroku.  The Heroku URL is:  agile-earth-8114.herokuapp.com

**Comment by brianburridge** [comment]
@markbiz41 you should also add a description to the rake task so that it shows up in the output of `rake -T`. Notice when you run that in your app now, that your rake task isn't listed there.

Also, you still don't have the postgres gem in your Gemfile for development, so I cannot run the app, or the raks tasks locally.

**Comment by markbiz41** [comment]
@brianburridge 
Assignment #45 is done.

https://github.com/markbiz41/pinterest/commit/abe0f5ddd1f00abb83e2ab947bb034e020c3d884

**Comment by brianburridge** [comment]
:+1:
