### ISSUE TITLE
Debugging a Rails Application

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#49]
_This is assignment 48 and is due on Mar 11, 2015._
- Read about ri [Up and Running With Ruby Interactive](http://samuelmullen.com/2012/01/up-and-running-with-ruby-interactive-ri/), [5 Reasons You Should Use ri To Read Ruby Documentation](http://www.jstorimer.com/blogs/workingwithcode/7766081-5-reasons-you-should-use-ri-to-read-ruby-documentation)
- Try [Dash](http://kapeli.com/dash)
- Try [OmniRef](https://www.omniref.com/)
- Sign up to use the [Suncoast Dev Slack](http://suncoast.io)
- Install the [better_errors gem](https://github.com/charliesome/better_errors) in your Pinterest application. Create an error to see how it works.
- Read about the [Rails logger](http://guides.rubyonrails.org/debugging_rails_applications.html) and implement some lines in your controller. Output an instance variable using the `.inspect` method to the log. Paste the section of your log file in a comment in this issue. In an issue comment direct me to where you have added the logger statements. (Yes, in this case you can check logger statements in).
- Read about using the [pry console debugger](https://github.com/nixme/pry-debugger) and try it in a controller action.

**Comment by markbiz41** [comment]
@brianburridge 

```
Started GET "/" for 127.0.0.1 at 2015-03-20 14:55:12 -0400
Processing by HomeController#index as HTML
  Pin Load (0.5ms)  SELECT  "pins".* FROM "pins" LIMIT 12 OFFSET 0
#<Pin id: 1, title: "title1", description: "desc1", board_id: 1, url: "http://cdn.desktopwallpapers4.me/media/thumbs_400x...", image: nil, user_id: 1, created_at: "2015-03-17 19:40:56", updated_at: "2015-03-17 19:40:56">
  Rendered pins/_pin.html.erb (0.4ms)
  Rendered pins/_pin.html.erb (2.4ms)
   (0.6ms)  SELECT COUNT(*) FROM "pins"
  Rendered home/index.html.erb within layouts/application (21.0ms)
  Rendered layouts/_messages.html.erb (0.1ms)
Completed 200 OK in 362ms (Views: 347.8ms | ActiveRecord: 4.7ms)


```

**Comment by markbiz41** [comment]
@brianburridge 
https://github.com/markbiz41/pinterest/blob/master/app/controllers/home_controller.rb#L4

**Comment by brianburridge** [comment]
@markbiz41 you wouldn't want to use `fatal` for logging debugging type information. Use the `info` or the `debug` instead next time.
