### ISSUE TITLE
Create a checklist for a new Rails app (group assignment)

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#50]
_This is assignment 49 and is due on Mar 11, 2015._
- Create a checklist of things to do to create a new Rails app, version control it in git, share it in GitHub and finally, get it running on Heroku.
- Use [Markdown](https://help.github.com/articles/markdown-basics/) to create the list. Put it in your _Assignments_ git repo and push it to GitHub.

**Comment by markbiz41** [comment]
@brianburridge 
Assignment #49 is my update49.rb file.

**Comment by brianburridge** [comment]
:+1:
