### ISSUE TITLE
ActiveRecord Query Interface

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#51]
_This is assignment 50 and is due on Mar 12, 2015._
- Reread the [ActiveRecord Query Interface doc](http://guides.rubyonrails.org/active_record_querying.html)
- Create a new Rails app, and the four models mentioned in the guide (with proper migrations): Client, Address, Order, Role
- Create just one controller (call it anything), with one action
- Make that one action the root
- Within that controller, try all the query samples from the query guide, section 1.1 (skipping the batches) and sections 2, 3, 4, and 5 and put a comment above as to why each is used.
- The view can just say "See controller" (no output is expected)
- No other views or scaffolds are required.
- You many need to create some basic seed data for the four models.
- Don't go overboard and make this too complex.

**Comment by markbiz41** [comment]
@brianburridge 
On assignment #50, I deployed to Github and Heroku.  The Heroku URL is:  sleepy-waters-2555.herokuapp.com

**Comment by brianburridge** [comment]
Would like to see some seed data in here so that I can run it. That's what the 2nd to last bullet was referring to.

Also you skipped a bunch of queries from section 1.1 that need to be in the controller so you understand how they work.

**Comment by markbiz41** [comment]
@brianburridge 
The seed data is now added to the assignment.  The Heroku URL is:  sleepy-waters-2555.herokuapp.com

**Comment by brianburridge** [comment]
:+1:
