### ISSUE TITLE
Using SASS

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#53]
_This is assignment 52 and is due on Mar 17, 2015._
- [x] Read the [Asset Pipeline Rails guide](http://guides.rubyonrails.org/asset_pipeline.html)
- [x] Read through the [SASS Basics guide](http://sass-lang.com/guide)
- [x] Use SASS in one of your past apps, and ensure you do the following:
- [x] Change your application.css to be a SASS file and to use `import` statement instead of the require tree.
- [x] Ensure your custom css is listed in your layout file below bootstrap, so they override any bootstrap files
- [x] Create and use at least one partial. Suggestion: place a few color variables in a `colors` partial
- [x] Ensure the scaffold.css from the Rails scaffold generator is no longer in use
- [x] Use the `darken` function to have one color be auto darkened off of another.
- [x] Set your site's background color via a variable
- [x] Use a few "nested" styles
- [x] Setup [bourbon](http://bourbon.io/) in your app
- [x] Look through bourbon's mixins and use at least one in your app. Find them in the [documentation](http://bourbon.io/docs/)
- [x] Link to the repository for the app where you made these changes
- [x] Also link to the Heroku app where the changes are visible. Be sure to let me know which page to look at on the app if not the home page.

**Comment by markbiz41** [comment]
@brianburridge 
Completed assignment #52 

http://agile-earth-8114.herokuapp.com/

https://github.com/markbiz41/pinterest/commit/4cbfe65ecd4fba5cdf7b557672aa6515eb1568c5

**Comment by brianburridge** [comment]
:+1:
