### ISSUE TITLE
Ruby Koans, First Half

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#55]
_This is assignment 54 and is due on Mar 19, 2015._
- Download the [RubyKoans](http://rubykoans.com/)
- Create a local git repo and a GitHub repo for them
- Complete 1 - 141 of the Koans
- Check in your work and push to GitHub
- Please provide a link to your new GitHub repo for the Koans

**Comment by markbiz41** [comment]
@brianburridge 
Completed assignment #54 up to 141.  The link for the new Github.com repo is:   https://github.com/markbiz41/koans.git

**Comment by brianburridge** [comment]
:+1:
