### ISSUE TITLE
Intro to JS and jQuery- in class

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#59]
_This is assignment 58 and is due on Mar 25, 2015._
- Read through this [JavaScript Basics](http://jqfundamentals.com/chapter/javascript-basics) and put some of the examples in your JS and ensure they run, show the proper output in the console and that you understand the basics.
- Note: Use `console.log` where the demo shows just `log`.
- Note: The _this_ explanation is a tricky thing in JavaScript. Don't get bogged down by it. jQuery will help with that.
- Check the two HTML pages and two JS pages we created in class (and perhaps a css if you used one).

**Comment by markbiz41** [comment]
@brianburridge 
Assignment #58 done in class.

**Comment by markbiz41** [comment]
file:///Users/markweinberg/theironyard/assignments/jquery.html

**Comment by brianburridge** [comment]
@markbiz41 That's a link to a file on your harddrive. Did you check your files in? There should be 4 of them.

**Comment by markbiz41** [comment]
@brianburridge 
I had to make a change because I had everything as a file and then created a folder and then put the files in there.  Assignment #58 is done.  Disregard file comment from 5 days ago.  assignment58 is where it is.

**Comment by brianburridge** [comment]
:+1:
