### ISSUE TITLE
Creating Variables and Literals

### ISSUE THREAD

**Issue by brianburridge** [markbiz41/Assignments#7]
_This assignment is due on Jan 28, 2015._
- Create code for each comment in [this gist](https://gist.github.com/brianburridge/79de494772daf7976ea9)
- Run the code and paste the output into your issue as a comment for this assignment
- It should list all the proper class names and all class tests should result in 'true'
- Before you run it, can you guess what will happen with the constant code you've created?

**Comment by markbiz41** [comment]
https://gist.github.com/brianburridge/79de494772daf7976ea9

**Comment by markbiz41** [comment]
https://gist.github.com/markbiz41/30a51632f60cab2bf2e9

**Comment by brianburridge** [comment]
@markbiz41 lines 4, 12, 35, and 41 aren't correct

**Comment by markbiz41** [comment]
@brianburridge 
https://gist.github.com/markbiz41/30a51632f60cab2bf2e9/revisions

**Comment by brianburridge** [comment]
Much better. There is still an issue with the constant part of it. You aren't outputting the constant.

**Comment by markbiz41** [comment]
@brianburridge 
https://gist.github.com/markbiz41/056e49c7887f83d2cadf

**Comment by brianburridge** [comment]
@markbiz41 I don't see any difference. Let's talk about this tomorrow afternoon.

**Comment by brianburridge** [comment]
@markbiz41 great to see you get this checked into GitHub, however, this code does not run. Be sure you are running it by using:

```
ruby assignment7.rb
```

**Comment by markbiz41** [comment]
@brianburridge 
Assignment #7 re-done and working in Terminal.

**Comment by brianburridge** [comment]
@markbiz41 so the problem with this code is the end part with the constant. The assignment wants you to assign a constant (you called it `FAR`). Then assign it another value.

But in your code, instead of assigning it another value, you have this code:

```
puts FAR == 26
```

Which puts the result of checking to see if FAR is equal to the number 26. That will produce a true or a false.

We are trying to change a constant variable so you can see the warning that Ruby gives.

**Comment by brianburridge** [comment]
When I try and run this I get an error. Be sure you always run your apps before turning them. I think when you do you'll know the problem right away.

**Comment by markbiz41** [comment]
@brianburridge 
You saw my computer and said you would mark this assignment completed.

**Comment by brianburridge** [comment]
Yep, already closed it. And it's behaving the same way on other's computers too.
